name: netdisco

services:
  netdisco-postgresql:
    image: netdisco/netdisco:latest-postgresql
    container_name: netdisco-postgresql
    hostname: netdisco-postgresql
    init: true
    restart: always
    volumes:
      - nd-pgdata-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: netdisco
      POSTGRES_USER: netdisco
      POSTGRES_PASSWORD: ${NTS_PASSWORD}

  netdisco-backend:
    image: netdisco/netdisco:latest-backend
    container_name: netdisco-backend
    hostname: netdisco-backend
    init: true
    restart: always
    volumes:
      - nd-sitelocal-volume:/home/netdisco/nd-site-local
      - nd-config-volume:/home/netdisco/environments
      - nd-logs-volume:/home/netdisco/logs
    environment:
      NETDISCO_DOMAIN: discover
      NETDISCO_DB_HOST: netdisco-postgresql
      NETDISCO_ADMIN_USER: "nts-admin"
      NETDISCO_DB_USER: netdisco
      NETDISCO_DB_PASS: ${NTS_PASSWORD}
    depends_on:
      - netdisco-postgresql

  netdisco-web:
    image: netdisco/netdisco:latest-web
    container_name: netdisco-web
    hostname: netdisco-web
    init: true
    restart: always
    volumes:
      - nd-sitelocal-volume:/home/netdisco/nd-site-local
      - nd-config-volume:/home/netdisco/environments
      - nd-logs-volume:/home/netdisco/logs
    environment:
      NETDISCO_DOMAIN: discover
      NETDISCO_DB_HOST: netdisco-postgresql
      NETDISCO_ADMIN_USER: "nts-admin"
      NETDISCO_DB_NAME: netdisco
      NETDISCO_DB_USER: netdisco
      NETDISCO_DB_PASS: ${NTS_PASSWORD}
    ports:
      - "5000:5000"
    depends_on:
      - netdisco-postgresql

  netdisco-do:
    image: netdisco/netdisco:latest-do
    container_name: netdisco-do
    init: true
    hostname: netdisco-backend
    volumes:
      - nd-sitelocal-volume:/home/netdisco/nd-site-local
      - nd-config-volume:/home/netdisco/environments
    environment:
      NETDISCO_DOMAIN: discover
      NETDISCO_DB_HOST: netdisco-postgresql
      NETDISCO_DB_NAME: netdisco
      NETDISCO_DB_USER: netdisco
      NETDISCO_DB_PASS: ${NTS_PASSWORD}
    depends_on:
      - netdisco-postgresql
    profiles:
      - cli-manual

volumes:
  nd-pgdata-volume:
  nd-sitelocal-volume:
  nd-config-volume:
  nd-logs-volume:
